version: 2
updates:
  # Root JS/TS project
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(tools)"
    groups:
      all:
        patterns:
          - "*"

  # UI subproject
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(ui)"
    ignore:
      # Dependabot doesn't respect semver ranges in package.json
      # See: https://github.com/dependabot/dependabot-core/issues/5176
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vitest"
        update-types: ["version-update:semver-major"]
    groups:
      all:
        patterns:
          - "*"

  # Terraform (infra)
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(infra)"
    groups:
      all:
        patterns:
          - "*"
