name: UI CI

on:
  pull_request:
    paths:
      - "ui/**"
      - ".github/workflows/ui-ci.yml"
      - ".mise.toml"
      - ".remarkrc.js"
      - ".markdownlint.json"
      - ".yamllint"
      - "package.json"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Lint Markdown files
        run: mise run //:lint:markdown:check

      - name: Lint MDX files
        run: mise run //:lint:mdx:check

      - name: Lint YAML files
        run: mise run //:lint:yaml

      - name: Run checks
        run: mise run //ui:check

      - name: Build
        run: mise run //ui:build
